language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  - sudo apt-get install -y libsubunit-dev
  # for MaxMinDB support
  - sudo apt-get install -y libmaxminddb-dev
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - git clone --depth 50 https://github.com/proftpd/proftpd.git
  - cp mod_geoip2.c proftpd/contrib/
  - cd proftpd
  - ./configure --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_geoip2
  - make
  - make clean
  - ./configure --enable-devel=coverage --enable-tests --with-modules=mod_geoip2
  - make
  # Run `tidy -e -q mod_geoip2.html` for doc validation
